### ISSUE TITLE
How to crop or mask data before downloading?

### ISSUE THREAD

**Issue by Technew94** [multiply-org/sar-pre-processing#17]
Dear authors,
Thanks for your great works for the S1 data searching, preprocessing and downloading.

Here's one question, have you ever build a function to mask or crop S1 to some specific area before downloading? I'm trying to using it to build a time-series database, but after my searching, it is too big which is too space consuming.
Do you have any suggestions on this problem?

All the best

**Comment by McWhity** [comment]
If you want to use S1 SLC data you have to download one entire S1 scene before subsetting to your area of interest as well as preprocessing. You could use the [jupyter notebook for preprocessing a single image](https://github.com/multiply-org/sar-pre-processing/blob/master/docs/notebooks/default_process_single_image.ipynb). After subsetting (and pre-processing) you might delete all unnecessary files to save space. With a loop function (loop via days of interest) the entire subsetting (and pre-processing) and deletion of unnecessary files should be fairly easy to be automated.
If you want to use S1 GRD data and you have limited space and processing power another option might be the use of the Google Earth Engine. There you can search, process and subset S1 GRD time series data in the cloud and download only the needed output files. 
I hope that helps.

**Comment by Technew94** [comment]
> If you want to use S1 SLC data you have to download one entire S1 scene before subsetting to your area of interest as well as preprocessing. You could use the [jupyter notebook for preprocessing a single image](https://github.com/multiply-org/sar-pre-processing/blob/master/docs/notebooks/default_process_single_image.ipynb). After subsetting (and pre-processing) you might delete all unnecessary files to save space. With a loop function (loop via days of interest) the entire subsetting (and pre-processing) and deletion of unnecessary files should be fairly easy to be automated. If you want to use S1 GRD data and you have limited space and processing power another option might be the use of the Google Earth Engine. There you can search, process and subset S1 GRD time series data in the cloud and download only the needed output files. I hope that helps.

Hi there,

Thanks for your response in a very short time, according to your answer, I think GEE is more suitable for my current works.
Thanks again and hope all the best!
