### ISSUE TITLE
Question regarding output file

### ISSUE THREAD

**Issue by simtrax** [multiply-org/sar-pre-processing#19]
Hi!

In the workflow I'm building I will most certainly process one scene at a time, my plan is then to store data as GeoTIFF for further processing.  
The SenSARP application stores the output as .nc files that are not georeferenced.  
Is there any ideas on how to output georeferenced GeoTIFF files instead?

Thanks!

**Comment by McWhity** [comment]
I added a second output format option for single file processing. Branch [def](https://github.com/multiply-org/sar-pre-processing/tree/dev)

If you add the following line to your config file 
```
single_file: 'yes'
single_file_output: 'tif'
```
the output files in folder step3 should be tif. But in that case the creation of a nedcdf stack will not work.
